.travis.yml
This should fix travis builds for the `audio` branch
=> add libasound2-dev dependency

pixelgl/window.go
Reason: 
This helps to implement fullscreening on the monitor the current application window is on which is useful if you have multiple monitors.
Eg. 
```
currentWindowPosition := win.GetPos()
for _, m := range pixelgl.Monitors() {
x, y := m.Position()
w, h := m.Size()
bounds := pixel.R(x, y, x+w, y+h)
if bounds.Contains(currentWindowPosition) {
win.SetMonitor(m)
break
}
}
```
=> Add GetPos function to window

pixelgl/input.go, pixelgl/window.go
This change mirrors the change done in the master branch
(see #78) for users of gl2.1, to provide access to polling
of events without rendering the screen.
Updates #26.
=> pixel/pixelgl: export UpdateInput

examples/community/video-modes/README.md, examples/community/video-modes/main.go, pixelgl/monitor.go, pixelgl/window.go
I added support for video modes as discussed in https://github.com/faiface/pixel/issues/113.
I also added a community example on how to use video modes.
Just tell me if there is something that should be done differently. I'm new to the project :)
I have not changed the API just extended it by two functions:
`func (w *Window) SetVideoMode(vm VideoMode)`, `func (m *Monitor) VideoModes() (vmodes []*VideoMode)` and a struct: `VideoMode`.
=> Adds video mode support and a community example for its usage.

.travis.yml
Update `.travis.yml` 
CI installs missing 3rd party dependencies that are only for `example/amidakuji`
=> CI support for example/amidakuji

geometry.go
It's like very small typo in comment, that I wonder if anyone's ever going to notice xD
Comment says it's a 3x2 Matrix but it's actually a 2x3 Matrix according to Wiki page.
https://github.com/faiface/pixel/issues/115
https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix#matrix
=> fix typo for matrix

pixelgl/canvas.go, pixelgl/glshader.go
I wanted to get this done before going version 0.8
This PR is to standardize the GLSL variable naming we use. There is no one official standard however there are plenty of common defacto standards. I went with what I think is best overall:
Any variables going into the vertex shader are attributes; so any attribute variable should begin with a lowercase a. Example:
```
in vec2  aPosition;
in vec4  aColor;
in vec2  aTexCoords;
in float aIntensity;
```
Any variables being sent to the fragment shader from the vertex shader are varyings; so any varying variable should begin with a lowercase v. Example:
```
// Vertex Shader would use:
out vec4  vColor;
out vec2  vTexCoords;
out float vIntensity;
// Fragment Shader would use:
in vec4  vColor;
in vec2  vTexCoords;
in float vIntensity;
```
Any …
=> standardized glsl variable naming

README.md
Hello Michal,
first let me tell you that this is a very cool game library that you have created! In the past I have created a lot of little games and other programs in Go, I even have [my own little game library](https://github.com/gonutz/prototype) which does a very similar job but has not as many features as yours.
The next [Ludum Dare](https://ldjam.com/) is coming up and I wanted to try using someone else's engine. Looking through the options I found yours very delightful, especially your little gopher game :-)
In order to get to know your engine in preparation, I ported my last Ludum Dare entry to it. This pull request is mainly to let you know about it (I know how cool it is to see others use your creations) and to say thank you for your effort to create something cool for the open …
=> Add No-Brain Jogging to examples

pixelgl/glshader.go
Adding the position out from vertex shader makes us skip computation of position in the fragment shader based on gl_FragCoord.
This is needed if creating fragment shaders based on some uniform positions for distance calculations like below.
float distance = sqrt(pow(vPosition.x-uPos.x, 2) + pow(vPosition.y-uPos.y, 2))
If we don't provide vPosition I think we need the screen resolution as uniforms to the fragment shader in order to calculate the position based on gl_FragCoord. Correct me if I'm wrong!
=> Added position as out variable from vertex shader.

pixelgl/input.go, pixelgl/joystick.go, pixelgl/window.go
Hey! This implements a way of doing Joystick input in pixel. I'm opening this PR now so that we can discuss if this is the right way to go about this before I get any further! The current implementation appears to be working but has not been thoroughly tested. 
I've tried to follow the patterns used for keyboard input by updating an internal state on each `UpdateInput` call. This tracks buttons and axis between each call allowing for functionality such as `JoystickJustPressed`. As the joystick state is kept globally instead of on a window, it will retrieve the latest state on each poll rather than registering callbacks as the keyboard input does.
To keep games safe, calling any of the axis or button functions will return `false` (button) or `0` (axis) if the joystick/button is invalid …
=> Added joystick input

pixelgl/joystick.go
This correctly allows for the use of `Joystick16` as per the issue in #155. It also adds `JoystickLast` as a helper.
=> Correctly index joysticks in internal state (fixes #155)

geometry.go, geometry_test.go
This PR fixes problems with `Matrix.Unproject` when rotated matrix is used. 
See #159
=> Fix Matrix.Unproject problem with rotated matrix

pixelgl/input.go
Hi, we updated an exported function comment based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

geometry.go, geometry_test.go
This adds a new geometric shape, a `Line`, made of two `Vec`s
Methods include intersections with other `Line`s, `Rect`s and `Circle`s (as well as visa-versa), moving, rotating and others.  All functions have tests for them.
There was discussion about whether you wanted a separate repo for collisions, and it's your repo so no problem if that's the decision; personal view: it makes sense to me for this code to be in Pixel.
Please let me know if you'd like anything changed/fixed (although should all be working!) or discussed.
Cheers
=> Add line geometry

geometry.go, geometry_test.go
Resolves #175 
This solution fixes the problem by only requiring 6 decimal places of accuracy.  This works for the additional test cases (previously broken), and is making https://github.com/faiface/pixel-examples/pull/16 work perfectly consistently.
Given that no one will be able to see 0.000001 of a pixel difference, I think this solution is fit for purpose.
=> Avoiding floating point rounding errors

sprite.go
Looks like #177 broke the sprite positioning because of [this line](https://github.com/faiface/pixel/blob/master/sprite.go#L107) using `.Position`, but expected position to be changed in the loop *afterwards*
Resolves #180
=> Setting position in correct order

data.go, data_test.go
~~**Raising as draft as I haven't had time to fully test this hasn't broken things. I'll mark as ready when I've checked some examples, etc**~~
Starting to address #46 - thought it'd be too big for one go.  This PR adds benchmarks for all exported methods of `pixel.TriangleData`, I've gone for the "low hanging fruit" and trimmed off a decent amount of heap allocation, and sped some of the more heavily used functions.
These are the benchmarks on the code unaltered:
```goos: linux
goarch: amd64
pkg: github.com/faiface/pixel
BenchmarkMakeTrianglesData/Small_slice-24         	 1000000	      1518 ns/op	    2240 B/op	       5 allocs/op
BenchmarkMakeTrianglesData/Large_slice-24         	    1000	   1779970 ns/op	 4086468 B/op	      21 allocs/op
BenchmarkTrianglesData_Len/Small_slice-24 …
```
=> Added TriangleData benchmarks and improvements

.travis.yml, README.md, go.mod, go.sum
This is a follow up on #185 and #189 
I noticed that running `go test ./...` yielded a change of the `go.mod` file which comes from a missing test dependency:
```
$ go mod why -m github.com/golang/freetype
github.com/faiface/pixel/text
github.com/faiface/pixel/text.test
github.com/golang/freetype/truetype
```
See also this part of the Go wiki: https://github.com/golang/go/wiki/Modules#why-does-go-mod-tidy-record-indirect-and-test-dependencies-in-my-gomod
To avoid such issues in the future I changed the `.travis.yml` to use the go modules during testing as well (which is nice for reproducible builds) and to fail if a dependency is missing from the `go.mod` file.
You can see a successful build here: https://travis-ci.org/fgrosse/pixel/builds/539207777
=> Fix Go modules

pixelgl/window.go
I want to create a non-full screen application that must display information on top of all other windows. This is supported in GLFW via the [`Floating` constant][1] which can be set via `glfw.WindowHint(…)`.
To support this feature I added a boolean `Floating` field to the `pixelgl.WindowConfig` type which is then used when setting up the window in `pixelgl.NewWindow()`. I then also saw there is an option to automatically add a preview for the window when I switch between applications so I added that as well in the same way (using `glfw.AutoIconify`).
I wasn't sure if and how I could write tests for those two fields. Also adding an example in that other repo didn't seem applicable here but let me know if there is anything more you would like me to do or change :)
[1]: …
=> Adding AutoIconify and Floating GLFW window hints

CHANGELOG.md, README.md
Hey Michal, as discussed in #194 I tried to collect significant changes for pixel that happened since `v0.8.0`.
To do this I relied mostly on https://github.com/faiface/pixel/compare/v0.8.0...master and some code browsing. Might be I missed something or got some commits wrong so you better double check if it makes sense to you :)
I also updated the `README.md` to point users to the `CHANGELOG.md` and I considered updating`CONTRIBUTING.md` but decided against it since there is not yet a lot of information about pull requests itself. If you want to add something there, maybe you want to get inspired by something I already use as standard in other projects: https://github.com/go-joe/joe/blob/master/CONTRIBUTING.md#pull-request-process
---
Some words about the proposed changelog format. I use …
=> Start to maintain a change log

pixelgl/window.go
Allow buffers to be swapped without polling input, offering decoupling symmetrical with that provided by UpdateInput.
Addresses issue #217
Related work: #79
Replacement for https://github.com/faiface/pixel/pull/218, which I somehow horribly borked.
=> Expose pixelgl.Window.SwapBuffers

go.mod, go.sum, pixelgl/input.go, pixelgl/joystick.go, pixelgl/monitor.go, pixelgl/run.go, pixelgl/window.go
Examples from the **pixel-examples** repository work good. Soon I will work on the gamepad support,
=> pixelgl has been ported to GLFW 3.3.

CHANGELOG.md, geometry.go, geometry_test.go
Resolves #210 
The issue was that the algorithm which gets the closest corner of a `Rect` to a point on the line did not account for that point being ZV, so always ignored it.  The algorithm now uses a pointer to ensure every closest vector is valid.
- Added tests to the closest point function to confirm vertical and horizontal lines work fine
- Added test as proposed in the issue to confirm the bug is fixed
- Replaced zero vector as the initial closest value with a pointer
- Updated change log
=> Fixing line intersection for lines through origin

CHANGELOG.md, pixelgl/window.go
Now that we have GLFW 3.3, we can use the `TransparentFramebuffer` window hint. This allows us to render windows which display transparent content so we can see other applications "through" it.
> GLFW_TRANSPARENT_FRAMEBUFFER specifies whether the window framebuffer will be transparent. If enabled and supported by the system, the window framebuffer alpha channel will be used to combine the framebuffer with the background. This does not affect window decorations. 
https://www.glfw.org/docs/3.3/window_guide.html#window_hints_wnd
=> Support glfw.TransparentFramebuffer window hint

CHANGELOG.md, pixelgl/window.go
This change allows users to specify the initial window position when they create the window. The advantage over calling `Window.SetPos(…)` after the window was created is, that the user will not see the window jump upon startup but it will directly spawn where we want it.
The method of marking the window at invisible is the suggested solution that is documented at [`glsw.CreateWindow(…)`][1]:
> To create the window at a specific position, make it initially invisible using the Visible window hint, set its position and then show it.
[1]: https://pkg.go.dev/github.com/go-gl/glfw@v0.0.0-20200420212212-258d9bec320e/v3.2/glfw?tab=doc#CreateWindow
=> Support setting an initial window position

pixelgl/joystick.go
Since **Pixel** now uses **GLFW v3.3**, I have implemented gamepad API. It works properly on **Windows** and Linux with **XBOX360** gamepad, but I don't have access to **Mac** computer and **PlayStation** gamepad nor my friends do, so it would be great if someone tested it. There's a [simple program](https://github.com/zergon321/pixel-joystick-test) to check your gamepad inputs. It also shows how to use the API.
=> Gamepad API added.

CHANGELOG.md, pixelgl/input.go
By using glfw.WaitEvent/WaitEventTimeout CPU time falls drastically (at the cost of less FPS). As the UI will be updated only when the OS notices that an event should be dispatched.
With this change users of pixel can choose between high FPS (window.UpdateInput) vs low FPS (window.WaitInput).
=> expose glfw.WaitEvent using Window.WaitInput

CHANGELOG.md, pixelgl/canvas.go, pixelgl/gltriangles.go
The Pixel UI project I'm working on needed this support as the triangles provided by imgui were not pre-clipped.
=> Adding Clipping rectangle support in GLTriangles

drawer.go
Using `pprof` to profile a game prototype where I was seeing some stuttering, I found I was getting a bottleneck iterating over the map `d.targets` within `Drawer.Dirty`, with the time mostly being taken up by `runtime.mapiternext`. Since it's looping over all the values, I thought I'd try indexing those values with a slice instead. From my quick measurements, it cleared up the problem right away (from taking up ~5s out of 30 seconds sampled, to ~.3s).
The changes here are pretty simple. I'm not sure if you'd like more evidence/rigor in demonstrating the perf improvement, but I think that for a large enough cardinality the perf benefits of looping over a slice as opposed to a map are well known (see e.g. "Test 4" [here](https://boltandnuts.wordpress.com/2017/11/20/go-slice-vs-maps/)). …
=> Use slice for range in Drawer.Dirty(), to improve performance

go.mod, pixelgl/window.go
Accessing and Changing System Clipboard using Clipboard() and SetClipboard()
=> Clipboard Support

geometry.go, text/text.go
This PR adds the concept of *anchors* to align elements.
It adds:
- `type Anchor`: *a vector used to define anchors, such as `Center`, `Top`, `TopRight`, etc.*;
- `func (Anchor) String() string`: *returns the string representation of an anchor.*;
- `func (*Rect) AnchorPos(anchor Anchor) Vec`: *returns the ~~absolute~~ position of the given anchor of the Rect.*;
- ~~edit: `func (*Rect) AnchorTo(Anchor)`: *updates the Rect position to align it on the given anchor.*~~
- edit: `func (Rect) AlignedTo(Anchor) Rect`: *returns the rect moved to be aligned on the given anchor.*
- ~~edit: `func (Matrix) Aligned(Rect, anchorPos AnchorPos) Matrix`: *moves everything to align the given rectangle on the given anchor position.*~~
- edit: `func (*Text) AlignedTo(pixel.Anchor) *Text`: *returns the text …
=> Add AnchorPos struct and functions

pixelgl/input.go, pixelgl/window.go
Hi. Great Library.
I noticed that some of my mouse click inputs for "JustPressed" would be missed if I click and release really fast. I tracked it down to the edge case where I click and release inside the same input frame. I modified input.go to track events rather than use the polled data (currInp and prevInp) for "JustPressed" and "JustReleased".
Let me know what you think.
Thanks,
Jacob
PS - Test Program - Just click as fast as you can to see if your inputs are also dropped (You can use go.mod replace to test my fork if you like)
```
package main
import (
"log"
"github.com/faiface/pixel"
"github.com/faiface/pixel/pixelgl"
)
func main() {
pixelgl.Run(runGame)
}
func runGame() {
cfg := pixelgl.WindowConfig{
Title:  "Pixel Rocks!",
Bounds: pixel.R(0, 0, 1024, 768),
VSync:  true,
}
win, …
```
=> Added input event tracking to prevent missed inputs

README.md
Adds two entries to README.MD under Related Repositories heading:
- [spriteplus](https://github.com/cebarks/spriteplus) Basic `SpriteSheet` and `Animation` implementations
- [pixelutils](https://github.com/dusk125/pixelutils) Variety of game related utilities (sprite packer, id generator, ticker, sprite loader, voronoia diagrams)
=> Add 2 related repos

rectangle.go, rectangle_test.go
I updated the Rect.Intersects function to use inclusive operators so that if only the edge of two rectangles is touching, it won't be considered overlapping, like how Intersect works.
I also added some rectangle v rectangle tests, replacing some benchmarks that weren't really doing anything.
=> Fixing #277: Rect.Intersect and Rect.Intersects now have consistent behavior

CHANGELOG.md, pixelgl/window.go
This PR adds a new WindowConfig value: SamplesMSAA. 
When this is set to a power of 2, it will enable MSAA for the window.
=> Add Multisample Anti-aliasing support

batch.go, drawer.go, sprite.go, text/text.go
Recently I attempted to create a video player in **Go**. I decoded video playback with [Reisen](https://github.com/zergon321/reisen) and  tried to play each frame using `sprite.Set()` and then `sprite.Draw()` but I encountered an issue with RAM consumption. **Pixel** saves each picture the sprite receives through `sprite.Set()`. When we play a video, there gonna be a lot of different pictures going to the sprite. But there's no need for them after they were played on the screen.
That's why I think there's no need to make all the sprites able to cache incoming pictures. I implemented `Cached` parameter for `Drawer` and `SetCached()` method for `Sprite` so the user can disable picture caching for the sprite for a period of time or forever.
Here's a snippet of code that produces random …
=> Added an opportunity to disable caching for sprites
