faiface/pixel

- pixelgl/canvas.go
Let me know if there's a better naming scheme, or if something else makes better sense to you.
> fix for 'texture' as a variable error, closes #4

- pixelgl/window.go
Fixes: https://github.com/faiface/pixel/issues/9
> Add ability to hide the cursor

- pixelgl/window.go
Fixes: https://github.com/faiface/pixel/issues/10
> Add support for setting an icon

- data.go
- geometry.go
- imdraw/imdraw.go
- pixelgl/canvas.go
- pixelgl/gltriangles.go
This is some reasonably straightforward performance tweaking, mostly broken out into distinct commits. For my test case, which was shoving ~88k points and then calling Line(1), I went from ~9fps to ~22fps on my hardware. Nothing obviously broke, but be aware that not everything here has been tested fully.
> performance tweaking

- data.go
- geometry.go
- imdraw/imdraw.go
- pixelgl/canvas.go
- pixelgl/gltriangles.go
> revised performance tuning pull request

- .travis.yml
- README.md
Adding CI can help with code review and prevent compilation errors
This adds initial support for Linux tests
Preferably before merging this, travis needs to be set up:
1. log in to travis-ci.org
2. activate 'pixel' repo with slider
> Use travis-ci

- geometry.go
- geometry_test.go
- Fixed order of operations in Resized function which essentially made all resizes anchor at the origin
- Added some simple test cases
> Fix Rectangle "Resized" function

- pixelgl/window.go
> Added SetPos to pixelgl.Window

- geometry_test.go
Made the geometry tests a bit neater.
Added several more test cases.
> Improve geometry tests

- pixelgl/input.go
- pixelgl/window.go
> pixelgl: export UpdateInput

- examples/community/parallax-scrolling-background/scrolling_background.go
Just a couple of small fixes I left behind ;)
> Parallax scroll

- text/atlas.go
- text/atlas_test.go
- text/text.go
- text/text_test.go
> Add Atlas7x13, Clear now sets Dot field to Orig

- examples/community/go-jetpack/jetpack.go
The go-jetpack example was loading a png file from disk every frame. I have corrected this.
> fixed accessing png files from disk every frame

- examples/community/scene/README.md
- examples/community/scene/main.go
This commit introduces a way to work with scenes by introducing a scene
type and a function to move between it.
> add a guide for making scenes

- geometry.go
- geometry_test.go
Resolves #161 
@faiface Please do critic my logic on this
> Fix circle intersect

- CONTRIBUTING.md
Hey, I am new to writing OpenGL applications and so far really enjoyed this library and the very well written tutorial in the wiki :+1: 
I was about to open another pull request when I noticed that there is a dead link in your `CONTRIBUTING.md` so I fixed that for you
See you soon in another PR :)
> Fixed link to examples repo in CONTRIBUTING.md

- geometry.go
Added the ZR for rectangle for both utility and consistensy with pixel.ZV
> Added ZR for zero rect

- geometry.go
> Revert "Fixed a couple of errors in methods comments"

- pixelgl/window.go
Resolves https://github.com/faiface/pixel/issues/213
> Added DisableCursor

- CHANGELOG.md
@fgrosse  Can you tell me if this is correct? :smile:
> Update CHANGELOG.md Unreleased Section

- CHANGELOG.md
- pixelgl/window.go
After #234 and #235 I was looking into if I can get the remaining GLFW window hints to work. I did not succeed with all of them and might have to do more research but wanted to submit what I have already.
Small PR again so should be easy to review
> Add window hints to created maximized or invisible windows

- pixelgl/window.go
Useful for GUI stuff, allows copying and pasting.
> Adding Clipboard get/set functions to window
